---

- hosts: nextcloud-server
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Update all packages to the newest version
      apt:
        update_cache: yes
        name: "*"
        state: latest
  become: yes
